server {
    listen 8080;
    server_name _;

    location = / {
        return 301 /logicap/;
    }

    location = /logicap {
        return 301 /logicap/;
    }

    location /logicap/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /logicap/index.html;
    }
}
